// 枚举文件，定义各种枚举

export const compareType = [
    {value: '文本', type: 'text'},
    {value: 'JSON对象', type: 'json'},
    {value: '数组内容', type: 'array'},
    {value: '逐行比较', type: 'line'},
    {value: '逐句比较', type: 'sentence'},
];

// export const wechatOpenInterfaceConfig = [{
//     "show_name": "基础支持",
//     "class_name": "api_info",
//     "content": [{
//         "name": "https://api.weixin.qq.com/cgi-bin/token",
//         "type": "args",
//         "method": "get",
//         "return_type": "json",
//         "show_name": "获取access_token接口 /token",
//         "args": [{
//             "name": "grant_type",
//             "diabled": "client_credential",
//             "required": true,
//             "tips": "获取access_token填写client_credential",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "appid",
//             "diabled": "",
//             "required": true,
//             "tips": "填写appid",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "secret",
//             "diabled": "",
//             "required": true,
//             "tips": "填写appsecret",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "http://file.api.weixin.qq.com/cgi-bin/media/upload",
//         "type": "args",
//         "method": "post",
//         "return_type": "json",
//         "show_name": "多媒体文件上传接口 /media/upload",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "type",
//             "diabled": "image,voice,video,thumb",
//             "required": true,
//             "tips": "媒体文件类型，分别有图片（image）、语音（voice）、视频（video）和缩略图（thumb）",
//             "method": "GET",
//             "type": "selector"
//         }, {
//             "name": "media",
//             "diabled": "",
//             "required": true,
//             "tips": "form-data中媒体文件标识，有filename、filelength、content-type等信息",
//             "method": "post",
//             "type": "file"
//         }]
//     }, {
//         "name": "http://file.api.weixin.qq.com/cgi-bin/media/get",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "下载多媒体文件接口 /media/get",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "media_id",
//             "diabled": "",
//             "required": true,
//             "tips": "媒体文件id",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "http://api.weixin.qq.com/cgi-bin/media/uploadimg",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "上传logo接口 /media/uploadimg",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "type",
//             "diabled": "image",
//             "required": false,
//             "tips": "图片（image）",
//             "method": "GET",
//             "type": "selector"
//         }, {
//             "name": "buffer",
//             "diabled": "",
//             "required": true,
//             "tips": "大小限制1MB，推荐像素为300*300，支持JPG格式",
//             "method": "POST",
//             "type": "file"
//         }]
//     }]
// }, {
//     "show_name": "向用户发送消息",
//     "class_name": "api_info",
//     "content": [{
//         "name": "https://api.weixin.qq.com/cgi-bin/message/custom/send",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "发送客服消息接口 /message/custom/send",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }]
// }, {
//     "show_name": "用户管理",
//     "class_name": "api_info",
//     "content": [{
//         "name": "https://api.weixin.qq.com/cgi-bin/user/get",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "获取关注者列表接口 /user/get",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "next_openid",
//             "diabled": "",
//             "required": false,
//             "tips": "获取关注用户列表偏移量，不填默认从头开始拉取",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/user/info",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "获取用户基本信息接口 /user/info",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "openid",
//             "diabled": "",
//             "required": true,
//             "tips": "目标用户的OPNEID",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/groups/get",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "查询分组接口 /groups/get",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/groups/create",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "创建分组接口 /groups/create",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/groups/update",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "修改分组名接口 /groups/update",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/groups/members/update",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "移动用户分组接口 /groups/members/update",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/groups/getid",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "查询用户分组id接口 /groups/getid",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }]
// }, {
//     "show_name": "自定义菜单",
//     "class_name": "api_info",
//     "content": [{
//         "name": "https://api.weixin.qq.com/cgi-bin/menu/create",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "自定义菜单创建接口 /menu/create",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/menu/get",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "自定义菜单查询接口 /menu/get",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/menu/delete",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "自定义菜单删除接口 /menu/delete",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }]
//     }]
// }, {
//     "show_name": "推广支持",
//     "class_name": "api_info",
//     "content": [{
//         "name": "https://api.weixin.qq.com/cgi-bin/qrcode/create",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "创建二维码ticket接口 /qrcode/create",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://mp.weixin.qq.com/cgi-bin/showqrcode",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "换取二维码 /showqrcode",
//         "args": [{
//             "name": "ticket",
//             "diabled": "",
//             "required": true,
//             "tips": "获取的二维码ticket",
//             "method": "GET",
//             "type": "string"
//         }]
//     }]
// }, {
//     "show_name": "消息接口调试",
//     "class_name": "callback_info",
//     "content": [{
//         "name": "文本消息",
//         "show_name": "文本消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "text",
//             "required": true,
//             "tips": "消息类型（文本消息为 text ）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Content",
//             "diabled": "",
//             "required": true,
//             "tips": "消息类型（文本消息内容）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "MsgId",
//             "diabled": "",
//             "required": true,
//             "tips": "消息类型（消息id，64位整型）",
//             "method": "GET",
//             "type": "num"
//         }]
//     }, {
//         "name": "图片消息",
//         "show_name": "图片消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "image",
//             "required": true,
//             "tips": "消息类型（图片消息为 image ）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "PicUrl",
//             "diabled": "",
//             "required": true,
//             "tips": "图片链接",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "MsgId",
//             "diabled": "",
//             "required": true,
//             "tips": "消息id，64位整型",
//             "method": "GET",
//             "type": "num"
//         }]
//     }, {
//         "name": "语音消息",
//         "show_name": "语音消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "voice",
//             "required": true,
//             "tips": "消息类型（语音消息为 voice ）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "MediaId",
//             "diabled": "",
//             "required": true,
//             "tips": "语音消息媒体id，可以调用相应接口拉取数据。",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Format",
//             "diabled": "",
//             "required": true,
//             "tips": "语音格式，如amr，speex等",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "MsgId",
//             "diabled": "",
//             "required": true,
//             "tips": "消息id，64位整型",
//             "method": "GET",
//             "type": "num"
//         }]
//     }, {
//         "name": "视频消息",
//         "show_name": "视频消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "video",
//             "required": true,
//             "tips": "消息类型（视频消息为 video ）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "MediaId",
//             "diabled": "",
//             "required": true,
//             "tips": "视频消息媒体id，可以调用相应接口拉取数据。",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ThumbMediaId",
//             "diabled": "",
//             "required": true,
//             "tips": "视频消息缩略图id，可以调用相应接口拉取数据。",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "MsgId",
//             "diabled": "",
//             "required": true,
//             "tips": "消息id，64位整型",
//             "method": "GET",
//             "type": "num"
//         }]
//     }, {
//         "name": "地理位置消息",
//         "show_name": "地理位置消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "location",
//             "required": true,
//             "tips": "消息类型（地理消息为 location ）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Location_X",
//             "diabled": "",
//             "required": true,
//             "tips": "地理位置维度",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "Location_Y",
//             "diabled": "",
//             "required": true,
//             "tips": "地理位置精度",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "Scale",
//             "diabled": "",
//             "required": true,
//             "tips": "地图缩放大小",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "Label",
//             "diabled": "",
//             "required": true,
//             "tips": "地理位置信息",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "MsgId",
//             "diabled": "",
//             "required": true,
//             "tips": "消息id，64位整型",
//             "method": "GET",
//             "type": "num"
//         }]
//     }, {
//         "name": "链接消息",
//         "show_name": "链接消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "link",
//             "required": true,
//             "tips": "消息类型（地理消息为 link ）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Title",
//             "diabled": "",
//             "required": true,
//             "tips": "消息标题",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Description",
//             "diabled": "",
//             "required": true,
//             "tips": "消息描述",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Url",
//             "diabled": "",
//             "required": true,
//             "tips": "消息链接",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "MsgId",
//             "diabled": "",
//             "required": true,
//             "tips": "消息id，64位整型",
//             "method": "GET",
//             "type": "num"
//         }]
//     }, {
//         "name": "事件消息",
//         "show_name": "事件消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "event",
//             "required": true,
//             "tips": "消息类型（地理消息为 event ）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Event",
//             "diabled": "",
//             "required": true,
//             "tips": "事件类型，有ENTER(进入会话)和LOCATION(地理位置)",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Latitude",
//             "diabled": "",
//             "required": false,
//             "tips": "地理位置维度，事件类型为LOCATION的时存在",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "Longitude",
//             "diabled": "",
//             "required": false,
//             "tips": "地理位置经度，事件类型为LOCATION的时存在",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "Precision",
//             "diabled": "",
//             "required": false,
//             "tips": "地理位置精度，事件类型为LOCATION的时存在",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgId",
//             "diabled": "",
//             "required": true,
//             "tips": "消息id，64位整型",
//             "method": "GET",
//             "type": "num"
//         }]
//     }, {
//         "name": "小程序widget事件消息",
//         "show_name": "小程序widget事件消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "event",
//             "required": true,
//             "tips": "消息类型（小程序widget消息为 event ）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Event",
//             "diabled": "wxa_widget_data",
//             "required": true,
//             "tips": "事件类型，小程序widget消息固定为wxa_widget_data",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Query",
//             "diabled": "",
//             "required": false,
//             "tips": "消息query参数",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Scene",
//             "diabled": "1",
//             "required": true,
//             "tips": "场景值，固定为1",
//             "method": "GET",
//             "type": "num"
//         }]
//     }]
// }, {
//     "show_name": "硬件接入api接口调试",
//     "class_name": "api_info",
//     "content": [{
//         "name": "https://api.weixin.qq.com/device/getqrcode",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "设备授权-获取deviceid和二维码 /device/getqrcode",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/authorize_device",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "设备授权-利用deviceid更新设备属性 device/authorize_device",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/verify_qrcode",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "验证设备二维码 device/verify_qrcode",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/get_stat",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "查询设备状态 device/get_stat",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "device_id",
//             "diabled": "",
//             "required": true,
//             "tips": "设备ID",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/bind",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "设备绑定-绑定成功通知 device/bind",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/compel_bind",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "设备绑定-强制绑定用户和设备 device/compel_bind",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/unbind",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "设备解绑-解绑成功通知 device/unbind",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/compel_unbind",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "设备绑定-强制绑定用户和设备 device/compel_unbind",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/get_openid",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "查询设备绑定的用户 device/get_openid",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "device_type",
//             "diabled": "",
//             "required": true,
//             "tips": "设备类型(公众账号原始ID)",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "device_id",
//             "diabled": "",
//             "required": true,
//             "tips": "设备ID",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/get_bind_device",
//         "type": "args",
//         "method": "GET",
//         "return_type": "json",
//         "show_name": "查询用户绑定的设备 device/get_bind_device",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "openid",
//             "diabled": "",
//             "required": true,
//             "tips": "用户的openid",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/transmsg",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "推送消息-发送设备消息 device/transmsg",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/device/transmsg",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "推送消息-发送设备状态消息 device/transmsg",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口的数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }]
// }, {
//     "show_name": "硬件接入消息接口调试",
//     "class_name": "callback_info",
//     "content": [{
//         "name": "设备向后台发送数据",
//         "show_name": "设备向后台发送数据",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "device_text",
//             "required": true,
//             "tips": "消息类型（设备消息为 device_text）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "DeviceType",
//             "diabled": "",
//             "required": true,
//             "tips": "设备类型(公众号ID)",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "DeviceID",
//             "diabled": "",
//             "required": true,
//             "tips": "设备ID",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Content",
//             "diabled": "",
//             "required": true,
//             "tips": "消息类型（文本消息内容）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "SessionID",
//             "diabled": "",
//             "required": true,
//             "tips": "会话ID（64位整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgId",
//             "diabled": "",
//             "required": true,
//             "tips": "消息类型（消息id，64位整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "OpenID",
//             "diabled": "",
//             "required": true,
//             "tips": "用户账号的OpenID",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "绑定/解绑消息",
//         "show_name": "绑定/解绑消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "device_event",
//             "required": true,
//             "tips": "消息类型（绑定/解绑消息填device_event）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Event",
//             "diabled": "",
//             "required": true,
//             "tips": "事件类型（绑定消息填 bind, 解绑消息填 unbind）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "DeviceType",
//             "diabled": "",
//             "required": true,
//             "tips": "设备类型(公众号ID)",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "DeviceID",
//             "diabled": "",
//             "required": true,
//             "tips": "设备ID",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Content",
//             "diabled": "",
//             "required": true,
//             "tips": "消息内容",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "SessionID",
//             "diabled": "",
//             "required": true,
//             "tips": "会话ID（64位整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "OpenID",
//             "diabled": "",
//             "required": true,
//             "tips": "用户账号的OpenID",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "请求绑定消息",
//         "show_name": "请求绑定消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "device_event",
//             "required": true,
//             "tips": "消息类型（请求绑定消息填device_event）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Event",
//             "diabled": "",
//             "required": true,
//             "tips": "事件类型（请求绑定消息填 request_bind）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "DeviceType",
//             "diabled": "",
//             "required": true,
//             "tips": "设备类型(公众号ID)",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "DeviceID",
//             "diabled": "",
//             "required": true,
//             "tips": "设备ID",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Content",
//             "diabled": "",
//             "required": true,
//             "tips": "消息内容",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "SessionID",
//             "diabled": "",
//             "required": true,
//             "tips": "会话ID（64位整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "OpenID",
//             "diabled": "",
//             "required": true,
//             "tips": "用户账号的OpenID",
//             "method": "GET",
//             "type": "string"
//         }]
//     }, {
//         "name": "wifi设备连接状态订阅/退订消息",
//         "show_name": "wifi设备连接状态订阅/退订消息",
//         "type": "args",
//         "method": "POST",
//         "args": [{
//             "name": "URL",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者填写URL，调试时将把消息推送到该URL上",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "ToUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "开发者微信号",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "FromUserName",
//             "diabled": "",
//             "required": true,
//             "tips": "发送方帐号（一个OpenID）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "CreateTime",
//             "diabled": "",
//             "required": true,
//             "tips": "消息创建时间 （整型）",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "MsgType",
//             "diabled": "device_event",
//             "required": true,
//             "tips": "消息类型（填device_event）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "Event",
//             "diabled": "",
//             "required": true,
//             "tips": "事件类型（订阅设备状态 subscribe_status, 退订设备状态 unsubscribe_status）",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "DeviceType",
//             "diabled": "",
//             "required": true,
//             "tips": "设备类型(公众号ID)",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "DeviceID",
//             "diabled": "",
//             "required": true,
//             "tips": "设备ID",
//             "method": "GET",
//             "type": "string"
//         }, {
//             "name": "OpType",
//             "diabled": "",
//             "required": true,
//             "tips": "请求类型(0:退订, 1:心跳(心跳的处理方式跟订阅一样), 2:订阅)",
//             "method": "GET",
//             "type": "num"
//         }, {
//             "name": "OpenID",
//             "diabled": "",
//             "required": true,
//             "tips": "用户账号的OpenID",
//             "method": "GET",
//             "type": "string"
//         }]
//     }]
// }, {
//     "show_name": "卡劵接口",
//     "class_name": "api_info",
//     "content": [{
//         "name": "https://api.weixin.qq.com/card/create",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "创建卡劵接口 card/create",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "卡劵数据json包",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/card/qrcode/create",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "创建二维码ticket接口 /qrcode/create",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "card_id必填，其它选填",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/card/testwhitelist/set",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "设置测试白名单接口 /testwhitelist/set",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "填写微信号，示例 { \"username\":[\"usr1\",\"usr2\"] }",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/card/code/consume",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "核销卡劵接口 /code/comsume",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "code:需核销的Code码,必填。\n\rcard_id:卡券ID,创建卡券时use_custom_code填写true时必填,非自定义Code不必填写",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }]
// }, {
//     "show_name": "评论接口",
//     "class_name": "api_info",
//     "content": [{
//         "name": "https://api.weixin.qq.com/cgi-bin/comment/open",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "打开已群发文章评论接口 comment/open",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "请求json包，示例 { \"msg_data_id\":MSG_DATA_ID,\"index\":INDEX}",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/comment/close",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "关闭已群发文章评论接口 comment/close",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "请求json包，示例 { \"msg_data_id\":MSG_DATA_ID,\"index\":INDEX}",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/comment/list",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "查看文章评论数据接口 comment/list",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "请求json包，示例{ \"msg_data_id\":MSG_DATA_ID,\"index\":INDEX，\"begin\":BEGIN,\"count\":COUNT,\"type\":TYPE}",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/comment/markelect",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "精选评论接口 comment/markelect",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "请求json包，示例{ \"msg_data_id\":MSG_DATA_ID,\"index\":INDEX，\"user_comment_id\":USER_COMMENT_ID}",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/comment/unmarkelect",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "取消精选评论接口 comment/unmarkelect",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "请求json包，示例{ \"msg_data_id\":MSG_DATA_ID,\"index\":INDEX，\"user_comment_id\":USER_COMMENT_ID}",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/comment/delete",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "删除评论接口 comment/delete",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "请求json包，示例{ \"msg_data_id\":MSG_DATA_ID,\"index\":INDEX，\"user_comment_id\":USER_COMMENT_ID}",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/comment/reply/add",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "回复评论接口 comment/reply/add",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "请求json包，示例{ \"msg_data_id\":MSG_DATA_ID,\"index\":INDEX，\"user_comment_id\":USER_COMMENT_ID，\"content\":\"CONTENT\"}",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }, {
//         "name": "https://api.weixin.qq.com/cgi-bin/comment/reply/delete",
//         "type": "args",
//         "method": "POST",
//         "return_type": "json",
//         "show_name": "删除回复接口 comment/reply/delete",
//         "args": [{
//             "name": "access_token",
//             "diabled": "",
//             "required": true,
//             "tips": "调用接口凭证",
//             "method": "GET",
//             "type": "string",
//             "sync": true
//         }, {
//             "name": "body",
//             "diabled": "",
//             "required": true,
//             "tips": "请求json包，示例{ \"msg_data_id\":MSG_DATA_ID,\"index\":INDEX，\"user_comment_id\":USER_COMMENT_ID}",
//             "method": "POST",
//             "type": "content",
//             "parse_type": "json"
//         }]
//     }]
// }]



